### ISSUE TITLE
Можете помочь с веткой json?

### ISSUE THREAD

**Issue by nm17** [IngenerkaTeamNewYork/FootballManager#11]
Нужно исправить ветку `json`.

**Comment by mabramovsd** [comment]
Это, видимо, уже на уроке. Дома так и не смог нужный компилятор найти

**Comment by nm17** [comment]
@mabramovsd 
Вы `--std=c++11` не забыли написать?

**Comment by mabramovsd** [comment]
Все сложнее. Во-первых, unsupported GCC version (4.9 у меня). Скачал GCC 6, теперь не находит sfml. В общем, уже потратил час на попытку скомпилировать, и это немного надоело. Могу принести на урок свой ноут. Скомпилируешь - молодец :)

**Comment by nm17** [comment]
@mabramovsd Принесите. Там вроде все просто...
Какая версия Ubuntu у вас?

**Comment by mabramovsd** [comment]
Ubuntu 14.04.5 LTS

**Comment by nm17** [comment]
> Ubuntu 14.04.5 LTS

Можете сказать результат комманды `ubuntu-support-status`

**Comment by nm17** [comment]
@mabramovsd А вообще лучше будет если вы сделаете `sudo apt dist-upgrade`

**Comment by nm17** [comment]
@mabramovsd А у вас хотябы есть CMake?

**Comment by nm17** [comment]
@mabramovsd @sosiska2281337 Ветку удаляю из-за тонны быдлокода в ней.
