### ISSUE TITLE
Нужно проверить функцию IsInRange()

### ISSUE THREAD

**Issue by nm17** [IngenerkaTeamNewYork/FootballManager#12]
Благодаря тестам, я смог найти баг в функции isInRange().
Задача: полностью переделать.
@mabramovsd 
@sosiska2281337

**Comment by mabramovsd** [comment]
Допустим, футболисты у тебя квадратные. Тогда они пересекаются, если и по x, и по y между их центрами меньше двух радиусов. Это можно записать так:
```cpp
(abs (pos.x - this->pos.x) < 2 * this->radius) &&
abs (pos.y - this->pos.y) < 2 * this->radius))
```

Если футболисты у тебя круглые, тут другая история: расстояние между центрами меньше двух радиусов. Расстояние между точками - это корень из суммы квадратов разностей координат, так что получитсяя что-то такое
```cpp
((pos.x - this->pos.x) * (pos.x - this->pos.x) + 
(pos.y - this->pos.y) * (pos.y - this->pos.y) < 
4 * this->radius * this->radius)
```

**Comment by nm17** [comment]
@mabramovsd Я вроде исправил уже. Проверте.

**Comment by nm17** [comment]
Вроде все ок.

**Comment by mabramovsd** [comment]
В проверке, что игроки столкнулись
```cpp
for (auto &currentb : Bayern) {
    for (auto &opp : Real) {
        while (currentb.isInRange(opp)) {
            currentb.move(currentb.pos - currentb.posv + sf::Vector2f(rand() % 10, rand() % 10));
            opp.move(opp.pos - opp.posv + sf::Vector2f(rand() % 10, rand() % 10));
            std::cout << opp.pos.x << '\n';
            std::cout << currentb.pos.x << '\n';
        }
    }
}
```

  1. Надо проверять, что мы не вышли за пределы экрана
  2. Надо прибавлять не `sf::Vector2f(rand() % 10, rand() % 10)`, а, например, `sf::Vector2f(rand() % 11 - 5, rand() % 11 - 5)` чтобы игроки могли улететь и влево, и вправо.

**Comment by nm17** [comment]
@mabramovsd можете сказать как?

**Comment by mabramovsd** [comment]
Скорее всего сработает
```cpp
while (currentb.isInRange(opp) or 
currentb.pos.x > window.getSize().x or currentb.pos.x < 0 or 
currentb.pos.y > window.getSize().y or currentb.pos.y < 0 or 
opp.pos.x > window.getSize().x or opp.pos.x < 0 or 
opp.pos.y > window.getSize().y or opp.pos.y < 0)
```

Но голову на отсечение не дам)

**Comment by nm17** [comment]
https://github.com/IngenerkaTeamNewYork/FootballManager/blob/74a3953601782f917c566cf510e9cbe0d279d932/src/RoundObj.h#L87

Так сойдет?

**Comment by mabramovsd** [comment]
Ну да. Я примерно это и написал. Осталось проверить, что оно работает...

**Comment by nm17** [comment]
@mabramovsd 74a3953 <- тут уже сделано (нужно протестировать)
