### ISSUE TITLE
Всеравно не двигаются

### ISSUE THREAD

**Issue by nm17** [IngenerkaTeamNewYork/FootballManager#14]
Ветка `test-movement`.

**Comment by nm17** [comment]
@mabramovsd

**Comment by mabramovsd** [comment]
bounce у тебя вызывается внутри while (window.pollEvent(event)). Подозреваю, столкновение должно быть вне этого цикла

**Comment by nm17** [comment]
@mabramovsd Коммит f2cc4bf посмотрите. Все так и не заработало.

**Comment by nm17** [comment]
@mabramovsd

**Comment by mabramovsd** [comment]
https://yadi.sk/d/2_Ci0bu93PCad2
1) Позиции и вектора у тебя не копировались в конструкторе копирования
2) Как работает функция bounce - понятия не имею, но если вставить её код рядом с windows.draw все пашет. Может она использует значения, а не ссылки

**Comment by nm17** [comment]
@mabramovsd Спасибо за код.
