### ISSUE TITLE
Футболисты неправильно расставлены

### ISSUE THREAD

**Issue by nm17** [IngenerkaTeamNewYork/FootballManager#19]
Теперь красные забивают синим в 4 раза больше чем красным.

**Comment by nm17** [comment]
Fixed in 6e8d0efb04d1ff61763c85b85aa973a0f3ae7d1b

**Comment by michaabramov12345** [comment]
Это нормально. Мы вратаря с нападающим переставили (27 и 35 строки [здесь](https://github.com/IngenerkaTeamNewYork/FootballManager/blob/skills/OurTeam.h)), чтобы проверить, что скиллы правильно учитываются

И, кстати, не вижу смысла фиксить. На презентации на этом примере (Нойера с Родригесом) можно показать, как меняется счет, если обратно этих перцев переставить

А вот если бы это был прям продакшен-продакшен (например, на GooglePlay выложили бы), то да, это баг и его надо фиксить
