### ISSUE TITLE
Я залил релиз на гихаб

### ISSUE THREAD

**Issue by nm17** [IngenerkaTeamNewYork/FootballManager#27]
https://github.com/IngenerkaTeamNewYork/FootballManager/releases/tag/v1.1

@mabramovsd Проверте работает или нет

**Comment by mabramovsd** [comment]
Да, молодец. Я проверил, работает (правда, конкретно на моем компе немного через попу - все файлы ищет не в той папке :) )

Запускается командами
make 
и
./FootballManager

**Comment by nm17** [comment]
@mabramovsd Все скомпилированные файлы в папке build. Вы о них говорите?

**Comment by nm17** [comment]
+ файлы должны быть в вне папки с исходником

**Comment by mabramovsd** [comment]
Те, которые в build-е не пробовал открывать. Просто проект перекомпилировал. И он почему-то картинки и текстовики ищет на папку выше FootballManager. Ничего особо критичного (cmake скорее всего криво запускаю), просто особенность моего компьютера
