### ISSUE TITLE
Нужно случайно передвигать футболистов по полю.

### ISSUE THREAD

**Issue by nm17** [IngenerkaTeamNewYork/FootballManager#5]
У кого есть идеи?

**Comment by nm17** [comment]
@sosiska2281337 не забудь!

**Comment by sosiska2281337** [comment]
Ok

**Comment by nm17** [comment]
@sosiska2281337

**Comment by nm17** [comment]
@mabramovsd

**Comment by mabramovsd** [comment]
https://github.com/AbramovFedyaninTeam/game/blob/master/game.cpp
Правда движения тут не случайные, просто ещё один пример

**Comment by sosiska2281337** [comment]
Есть претензии? Сейчас залью коордтинаты 523, 451

2017-10-27 23:36 GMT+04:00 Mikhail Abramov <notifications@github.com>:

**Comment by nm17** [comment]
@mabramovsd сегодня будет урок?

**Comment by sosiska2281337** [comment]
да


2017-10-28 11:19 GMT+04:00 NeverMine17 <notifications@github.com>:

**Comment by nm17** [comment]
@sosiska2281337 @mabramovsd Нужна помощь с #11 #12

**Comment by sosiska2281337** [comment]
@NeverMine17 координаты сделаю на инженерке. Нет картинок с расстановкой в
папке. (хотя я все заливал)

2017-10-28 11:42 GMT+04:00 данил хохлов <danhoh22895@gmail.com>:
